WQ:CALCulate:BANDwidth:NDB
Q:CALCulate:BANDwidth:RESult
W:CALCulate:LLINe:ALL:DELete
WQ:CALCulate:LLINe:CONTrol:DOMain
Q:CALCulate:LLINe:FAIL
Q:CALCulate:LLINe:FAIL:RATIo
WQ:CALCulate:LLINe:FAIL:STOP:STATe
WQ:CALCulate:LLINe<n>:CONTrol:INTerpolate:TYPE
WQ:CALCulate:LLINe<n>:DATA
W:CALCulate:LLINe<n>:DATA:MERGe
W:CALCulate:LLINe<n>:DELete
WQ:CALCulate:LLINe<n>:RELAmpt[:STATe]
WQ:CALCulate:LLINe<n>:RELFreq[:STATe]
WQ:CALCulate:LLINe<n>:STATe
W:CALCulate:MARKer:AOFF
WQ:CALCulate:MARKer:FCOunt:RESolution
WQ:CALCulate:MARKer:FCOunt:RESolution:AUTO
Q:CALCulate:MARKer:FCOunt:X
WQ:CALCulate:MARKer:FCOunt[:STATe]
WQ:CALCulate:MARKer<n>:CPEak[:STATe]
R:CALCulate:MARKer<n>:DELTa[:SET]:CENTer
R:CALCulate:MARKer<n>:DELTa[:SET]:SPAN
WQ:CALCulate:MARKer<n>:FUNCtion
R:CALCulate:MARKer<n>:MAXimum:LEFT
R:CALCulate:MARKer<n>:MAXimum:MAX
R:CALCulate:MARKer<n>:MAXimum:NEXT
R:CALCulate:MARKer<n>:MAXimum:RIGHt
R:CALCulate:MARKer<n>:MINimum
WQ:CALCulate:MARKer<n>:MODE
WQ:CALCulate:MARKer<n>:PEAK:EXCursion
WQ:CALCulate:MARKer<n>:PEAK:SEARch:MODE
R:CALCulate:MARKer<n>:PEAK[:SET]:CF
WQ:CALCulate:MARKer<n>:PEAK:THReshold
R:CALCulate:MARKer<n>:PTPeak
W:CALCulate:MARKer<n>[:SET]:CENTer
W:CALCulate:MARKer<n>[:SET]:RLEVel
W:CALCulate:MARKer<n>[:SET]:STARt
W:CALCulate:MARKer<n>[:SET]:STEP
W:CALCulate:MARKer<n>[:SET]:STOP
WQ:CALCulate:MARKer<n>:STATe
WQ:CALCulate:MARKer<n>:TRACe
WQ:CALCulate:MARKer<n>:TRACe:AUTO
WQ:CALCulate:MARKer<n>:X
WQ:CALCulate:MARKer<n>:X:CENTer
WQ:CALCulate:MARKer<n>:X:POSition
WQ:CALCulate:MARKer<n>:X:POSition:CENTer
WQ:CALCulate:MARKer<n>:X:POSition:SPAN
WQ:CALCulate:MARKer<n>:X:POSition:STARt
WQ:CALCulate:MARKer<n>:X:POSition:STOP
WQ:CALCulate:MARKer<n>:X:READout
WQ:CALCulate:MARKer<n>:X:SPAN
WQ:CALCulate:MARKer<n>:X:STARt
WQ:CALCulate:MARKer<n>:X:STOP
Q:CALCulate:MARKer<n>:Y
WQ:CALCulate:MARKer:TABLe:STATe
WQ:CALCulate:MARKer:TRACking:STATe
WQ:CALCulate:NTData[:STATe]
##
:CALibration:[ALL]
:CALibration:AUTO
##
:CONFigure
:CONFigure:ACPower
:CONFigure:CHPower
:CONFigure:CNRatio
:CONFigure:EBWidth
:CONFigure:HDISt
:CONFigure:OBWidth
:CONFigure:PF
:CONFigure:SANalyzer
:CONFigure:TOI
:CONFigure:TPOWer
:COUPle Subsystem
:COUPle
##
:DISPlay:AFUnction:POSition
:DISPlay:ANNotation:CLOCk[:STATe]
:DISPlay:BRIGhtness
:DISPlay:ENABle
:DISPlay:MSGswitch:STATe
:DISPlay:UKEY:STATe
:DISPlay:WINdow:TRACe:GRATicule:GRID
:DISPlay:WINdow:TRACe:X[:SCALe]:SPACing
:DISPlay:WINdow:TRACe:Y:DLINe
:DISPlay:WINdow:TRACe:Y:DLINe:STATe
:DISPlay:WINdow:TRACe:Y[:SCALe]:NRLevel
:DISPlay:WINdow:TRACe:Y[:SCALe]:NRPosition
:DISPlay:WINdow:TRACe:Y[:SCALe]:PDIVision
:DISPlay:WINdow:TRACe:Y[:SCALe]:RLEVel
:DISPlay:WINdow:TRACe:Y[:SCALe]:RLEVel:OFFSet
:DISPlay:WINdow:TRACe:Y[:SCALe]:SPACing
##
:FETCh:ACPower
:FETCh:ACPower:LOWer
:FETCh:ACPower:MAIN
:FETCh:ACPower:UPPer
:FETCh:CHPower
:FETCh:CHPower:CHPower
:FETCh:CHPower:DENSity
:FETCh:CNRatio
:FETCh:CNRatio:CARRier
:FETCh:CNRatio:CNRatio
:FETCh:CNRatio:NOISe
:FETCh:EBWidth
:FETCh:HARMonics:AMPLitude:ALL
:FETCh:HARMonics:AMPLitude <n>
:FETCh:HARMonics[:DISTortion]
:FETCh:HARMonics:FREQuency:ALL
:FETCh:HARMonics:FREQuency <n>
:FETCh:HARMonics:FUNDamental
:FETCh:OBWidth
:FETCh:OBWidth:OBWidth
:FETCh:OBWidth:OBWidth:FERRor
:FETCh:TOIntercept
:FETCh:TOIntercept:IP3
:FETCh:TPOWer
##
:FORMat:BORDer
:FORMat[:TRACe][:DATA]
##
:HCOPy:ABORt
:HCOPy:IMAGe:COLor[:STATe]
:HCOPy:IMAGe:FTYPe
:HCOPy:IMAGe:INVert
:HCOPy:IMAGe:PTIMe
:HCOPy:IMAGe:QUALity
:HCOPy[:IMMediate]
:HCOPy:PAGE:ORIentation
:HCOPy:PAGE:PRINts
:HCOPy:PAGE:SIZE
:HCOPy:RESume
##
:INITiate Subsystem
:INITiate:CONTinuous
:INITiate[:IMMediate]
:INITiate:PAUSe
:INITiate:RESTart
:INITiate:RESume
##        
:INPut:IMPedance        
##
:MMEMory Subsystem
:MMEMory:DELete
:MMEMory:DISK:INFormation
:MMEMory:LOAD:CORRection
:MMEMory:LOAD:LIMit
:MMEMory:LOAD:MTABle
:MMEMory:LOAD:SETUp
:MMEMory:LOAD:STATe
:MMEMory:LOAD:TRACe
:MMEMory:MOVE
:MMEMory:STORe:CORRection
:MMEMory:STORe:LIMit
:MMEMory:STORe:MTABle
:MMEMory:STORe:PTABle
:MMEMory:STORe:RESults
:MMEMory:STORe:SCReen
:MMEMory:STORe:SETUp
:MMEMory:STORe:STATe
:MMEMory:STORe:TRACe
##
:OUTPut[:STATe]
##
:READ:ACPower
:READ:ACPower:LOWer
:READ:ACPower:MAIN
:READ:ACPower:UPPer
:READ:CHPower
:READ:CHPower:CHPower
:READ:CHPower:DENSity
:READ:CNRatio
:READ:CNRatio:CARRier
:READ:CNRatio:CNRatio
:READ:CNRatio:NOISe
:READ:EBWidth
:READ:HARMonics:AMPLitude:ALL
:READ:HARMonics:AMPLitude <n>
:READ:HARMonics[:DISTortion]
:READ:HARMonics:FREQuency:ALL
:READ:HARMonics:FREQuency <n>
:READ:HARMonics:FUNDamental
:READ:OBWidth
:READ:OBWidth:OBWidth
:READ:OBWidth:OBWidth:FERRor
:READ:TOIntercept
:READ:TOIntercept:IP3
:READ:TPOWer
##
[:SENSe]:ACPower:AVERage:COUNt
[:SENSe]:ACPower:AVERage[:STATe]
[:SENSe]:ACPower:AVERage:TCONtrol
[:SENSe]:ACPower:BANDwidth:ACHannel
[:SENSe]:ACPower:BANDwidth:INTegration
[:SENSe]:ACPower:CSPacing 
[:SENSe]:BANDwidth:EMIFilter:STATe
[:SENSe]:BANDwidth[:RESolution]
[:SENSe]:BANDwidth[:RESolution]:AUTO
[:SENSe]:BANDwidth:VIDeo
[:SENSe]:BANDwidth:VIDeo:AUTO
[:SENSe]:BANDwidth:VIDeo:RATio
[:SENSe]:CHPower:AVERage:COUNt
[:SENSe]:CHPower:AVERage[:STATe]
[:SENSe]:CHPower:AVERage:TCONtrol
[:SENSe]:CHPower:BANDwidth:INTegration
[:SENSe]:CHPower:FREQuency:SPAN
[:SENSe]:CNRatio:AVERage:COUNt.
[:SENSe]:CNRatio:AVERage[:STATe]
[:SENSe]:CNRatio:AVERage:TCONtrol
[:SENSe]:CNRatio:BANDwidth:INTegration
[:SENSe]:CNRatio:BANDwidth:NOISe
[:SENSe]:CNRatio:OFFSet
[:SENSe]:CORRection:CSET:ALL:DELete
[:SENSe]:CORRection:CSET:ALL[:STATe]
[:SENSe]:CORRection:CSET<n>:DATA
[:SENSe]:CORRection:CSET<n>:DATA:MERGe
[:SENSe]:CORRection:CSET<n>:DELete
[:SENSe]:CORRection:CSET<n>[:STATe]
[:SENSe]:CORRection:CSET<n>:X:SPACing
[:SENSe]:CORRection:CSET:TABLe:STATe
[:SENSe]:DEMod
[:SENSe]:DEMod:GAIN:AUTO
[:SENSe]:DEMod:GAIN:INCRement
[:SENSe]:DEMod:STATe
[:SENSe]:DEMod:TIME
[:SENSe]:DETector[:FUNCtion]
[:SENSe]:EBWidth:AVERage:COUNt
[:SENSe]:EBWidth:AVERage[:STATe]
[:SENSe]:EBWidth:AVERage:TCONtrol
[:SENSe]:EBWidth:FREQuency:SPAN
[:SENSe]:EBWidth:MAXHold:STATe
[:SENSe]:EBWidth:XDB
[:SENSe]:EXTRef[:STATe]
[:SENSe]:FREQuency:CENTer
[:SENSe]:FREQuency:CENTer:DOWN
[:SENSe]:FREQuency:CENTer:SET:STEP
[:SENSe]:FREQuency:CENTer:STEP:AUTO
[:SENSe]:FREQuency:CENTer:STEP[:INCRement]
[:SENSe]:FREQuency:CENTer:UP
[:SENSe]:FREQuency:OFFSet
[:SENSe]:FREQuency:SPAN 
[:SENSe]:FREQuency:SPAN:FULL
[:SENSe]:FREQuency:SPAN:PREVious
[:SENSe]:FREQuency:SPAN:ZIN
[:SENSe]:FREQuency:SPAN:ZOUT
[:SENSe]:FREQuency:STARt 
[:SENSe]:FREQuency:STOP
[:SENSe]:HDISt:AVERage:COUNt
[:SENSe]:HDISt:AVERage[:STATe]
[:SENSe]:HDISt:AVERage:TCONtrol
[:SENSe]:HDISt:NUMBers
[:SENSe]:HDISt:TIME
[:SENSe]:HDISt:TIME:AUTO[:STATe]
[:SENSe]:OBWidth:AVERage:COUNt
[:SENSe]:OBWidth:AVERage[:STATe]
[:SENSe]:OBWidth:AVERage:TCONtrol
[:SENSe]:OBWidth:FREQuency:SPAN
[:SENSe]:OBWidth:MAXHold:STATe
[:SENSe]:OBWidth:PERCent
[:SENSe]:POWer:ARANge
[:SENSe]:POWer:ASCale
[:SENSe]:POWer:ATUNe
[:SENSe]:POWer[:RF]:ATTenuation
[:SENSe]:POWer[:RF]:ATTenuation:AUTO
[:SENSe]:POWer[:RF]:GAIN[:STATe]
[:SENSe]:POWer[:RF]:MIXer:RANGe[:UPPer]
[:SENSe]:SIGCapture[:STATe]
[:SENSe]:SIGCapture:SIGC[:STATe]
[:SENSe]:SIGCapture:MAXHold[:STATe]
[:SENSe]:SIGCapture:RESet
[:SENSe]:SIGCapture:2FSK[:STATe]
[:SENSe]:SIGCapture:2FSK:RESet
[:SENSe]:SIGCapture:2FSK:MAXHold[:STATe]
[:SENSe]:SIGCapture:2FSK:PFSWitch
[:SENSe]:SIGCapture:2FSK:SIGNal
[:SENSe]:SIGCapture:2FSK:AMPUp
[:SENSe]:SIGCapture:2FSK:AMPDown
[:SENSe]:SIGCapture:2FSK:MARK1[:FREQ]
[:SENSe]:SIGCapture:2FSK:MARK1:Switch[:STATe]
[:SENSe]:SIGCapture:2FSK:MARK2[:FREQ]
[:SENSe]:SIGCapture:2FSK:MARK2:Switch[:STATe]
[:SENSe]:SWEep:COUNt
[:SENSe]:SWEep:COUNt:CURRent
[:SENSe]:SWEep:POINts
[:SENSe]:SWEep:TIME
[:SENSe]:SWEep:TIME:AUTO
[:SENSe]:SWEep:TIME:AUTO:RULes
[:SENSe]:TOI:AVERage:COUNt
[:SENSe]:TOI:AVERage[:STATe]  
[:SENSe]:TOI:AVERage:TCONtrol
[:SENSe]:TOI:FREQuency:SPAN
[:SENSe]:TPOWer:AVERage:COUNt
[:SENSe]:TPOWer:AVERage[:STATe] 
[:SENSe]:TPOWer:AVERage:TCONtrol 
[:SENSe]:TPOWer:LLIMit  
[:SENSe]:TPOWer:MODE  
[:SENSe]:TPOWer:RLIMit 
[:SENSe]:VSWR:FREFlect 
[:SENSe]:VSWR:NREFlect 
[:SENSe]:VSWR:RESet 
[:SENSe]:VSWR:STATe 
##
:SOURce:CORRection:OFFSet
:SOURce:POWer:LEVel:IMMediate:AMPLitude
:SOURce:POWer:MODE
:SOURce:POWer:SPAN
:SOURce:POWer:STARt
:SOURce:POWer:SWEep
:SOURce:TRACe:REF:STATe
:SOURce:TRACe:STORref
##
:STATus:OPERation:CONDition
:STATus:OPERation:ENABle
:STATus:OPERation[:EVENt]
:STATus:PRESet
:STATus:QUEStionable:CONDition
:STATus:QUEStionable:ENABle
:STATus:QUEStionable[:EVENt]
##
:SYSTem:BEEPer:STATe
:SYSTem:CLEar
:SYSTem:COMMunicate:APORt
:SYSTem:COMMunicate:BRMT
:SYSTem:COMMunicate:GPIB[:SELF]:ADDRess
:SYSTem:COMMunicate:LAN[:SELF]:AUToip:STATe
:SYSTem:COMMunicate:LAN[:SELF]:DHCP:STATe
:SYSTem:COMMunicate:LAN[:SELF]:IP:ADDress
:SYSTem:COMMunicate:LAN[:SELF]:IP:DNSServer
:SYSTem:COMMunicate:LAN[:SELF]:IP:GATeway
:SYSTem:COMMunicate:LAN[:SELF]:IP:SUBMask
:SYSTem:COMMunicate:LAN[:SELF]:MANuip:STATe
:SYSTem:COMMunicate:LAN[:SELF]:RESet
:SYSTem:COMMunicate:USB[:SELF]:ADDRess
:SYSTem:COMMunicate:USB[:SELF]:CLASs
:SYSTem:CONFigure:INFormation
:SYSTem:CONFigure:MESSage
:SYSTem:DATE
:SYSTem:ERRor[:NEXT]
:SYSTem:FSWItch[:STATe]
:SYSTem:KLOCk
:SYSTem:LANGuage
:SYSTem:LINemod:STATe
:SYSTem:LINemod:TYPe
:SYSTem:LKEY
:SYSTem:OPTions
:SYSTem:PON:TYPE
:SYSTem:PRESet
:SYSTem:PRESet:SAVE
:SYSTem:PRESet:TYPE
:SYSTem:SPEaker[:STATe]
:SYSTem:SPEaker:VOLume
:SYSTem:TIME
:SYSTem:TX:STATe
:SYSTem:TX:SWset
:SYSTem:TX:SWSTa
:SYSTem:USERkey:CONFirm
:SYSTem:USERkey:KEYCmd
:SYSTem:USERkey:STATe
:SYSTem:VERSion
##
:TRACe:AVERage:CLEar
:TRACe:AVERage:COUNt
:TRACe:AVERage:COUNt:CURRent
:TRACe:AVERage:RESet
:TRACe:CLEar:ALL
:TRACe[:DATA]
:TRACe:MATH:A
:TRACe:MATH:B
:TRACe:MATH:CONSt
:TRACe:MATH:PEAK[:DATA]
:TRACe:MATH:PEAK:POINts
:TRACe:MATH:PEAK:SORT
:TRACe:MATH:PEAK:TABLe:STATe
:TRACe:MATH:PEAK:THReshold
:TRACe:MATH:STATe
:TRACe:MATH:TYPE
:TRACe<n>:AVERage:TYPE
:TRACe<n>:MODE
##
:TRIGger:SEQuence:EXTernal:READy
:TRIGger:SEQuence:EXTernal:SLOPe
:TRIGger:SEQuence:SOURce
:TRIGger:SEQuence:VIDeo:LEVel
##
:UNIT:POWer